### ISSUE TITLE
Hardware kivu12 testing

### ISSUE THREAD

**Issue by ohmtech-rdi** [ohmtech-rdi/eurorack-blocks#184]
After the first `kivu12` board is assembled, make a first round of hardware test, before we test the software as in #180.

## Stage 1

- DPSM is not connected
- No front panel connected
- Lab supply: max 100mA for all outputs

Tasks:
- [x] Proper ±12V with small current consumption
- [x] Connect `kivu12/CI1` and  `kivu12/CI2` to 0V, 2.5V, -2.5V, 5V, -5V, Jumpers on position ±5V
   `DPSM/C4` and `DPSM/C5` are 0V, 2.5V, -2.5V, 5V, -5V
- [ ] ❌ Connect `kivu12/CI1` and  `kivu12/CI2` to 0V, 4V, 8V, Jumpers on position 0..10V
   `DPSM/C4` and `DPSM/C5` are -5V, -1V, 3V
- [x] Connect `DPSM/A2/A3/A9` to `GND`, `kivu12/B2` to xV, `DPSM/B9` is xV
- [x] Connect `DPSM/A2/A3/A9` to `GND`, `kivu12/B10` to xV, `DPSM/B10` is xV

## Stage 2

- DPSM is connected
- No front panel connected
- Lab supply: max 200mA for all outputs

Tasks:
- [x] Proper ±12V with small current consumption
- [x] Proper 3V3 on `kivu12/3V3`

**Comment by ohmtech-rdi** [comment]
When jumper position is 0..10V, whatever the input, the output is 10V for some reason.

The -5V voltage reference is proper, so we might have a problem with the schematics already.

**Comment by ohmtech-rdi** [comment]
When connecting the DPSM:
- 12V takes around 110mA
- -12V takes around 10mA
