### ISSUE TITLE
SDRAM write/read failure

### ISSUE THREAD

**Issue by ohmtech-rdi** [ohmtech-rdi/eurorack-blocks#212]
We have a problem with SDRAM in general. When soft or hard resetting the board, the SDRAM will return a different value than the one written for some portion of memories. Turning off the system and on again "correct" this problem. We don't yet whether this is caused by:
- Some sort of faulty board,
- A problem when setting up the SDRAM,
- Some other unknown problem.

For now, we consider that we can merge this PR, as this SDRAM problem doesn't seem to be related to the SDRAM implementation. What was tried and failed:
- We made sure to zero the entire SDRAM section at start, even if it is not needed,
- In the case of audio, when reading a NaN value, we return a 0 instead (this introduces a lot of noise, but this seems to "work", and somehow seems to indicate there are problems only over a certain number of addresses)
- We copied the `ValidateSDRAM` function from Daisy to give it a test. It seems it always find failures, somehow of a magnitude of 1 million words.

## Current Status 23 Dec 2021

Most likely a faulty board. Progress is paused until the manufacturer gets back to us.

## Current Status 06 Feb 2022

The board was faulty. The new board works perfectly.

## Tasks

- [x] Clone [DaisyExample](https://github.com/electro-smith/DaisyExamples)
- [x] Build all libraries and `patch_sm/HardwareTest`
- [x] Open project in VS Code
- [x] Run project and report
- [x] Rerun `patch_sm/HardwareTest` after a power cycle and with a serial monitor and report
- [x] While we are at it, check that SD works on `kivu12`
- [x] Mitigate

**Comment by ohmtech-rdi** [comment]
## Report

```console
$ git clone git@github.com:electro-smith/DaisyExamples.git
...
$ cd DaisyExamples/
$ ./rebuild_all.sh
... 
./rebuild_all.sh: line 4: ./ci/build_examples.py: Permission denied
$ ls -l ci/
total 40
-rwxr-xr-x  1 raf  staff  4920 Dec 15 11:37 build_dist.py
-rw-r--r--  1 raf  staff  1258 Dec 15 11:37 build_examples.py
-rwxr-xr-x  1 raf  staff   410 Dec 15 11:37 build_libs.sh
-rw-r--r--  1 raf  staff   347 Dec 15 11:37 local_style_check.sh
$ chmod 755 ci/build_examples.py
$ ./rebuild_all.sh
...
$ cd patch_sm/HardwareTest/
```

There is a test in `patch_sm` which is exactly what we need.
[](https://github.com/ohmtech-rdi/DaisyExamples/tree/master/patch_sm/HardwareTest)

However there is no serial console yet as said in the README file.
So use VS Code instead, there is a `.vscode` project in it.

- Launch VS Code
- Open `HardwareTest` project
- Run `Cortex Debug`

```console
> Executing task: make <

The terminal process failed to launch: Starting directory (cwd) "/Users/raf/Desktop/dev/DaisyExamples/patch_sm/libDaisy" does not exist.

Terminal will be reused by tasks, press any key to close it.
```

For some reason, `build_all_debug` in `launch.json` isn't really called, `make` only
is called and complains not to find `libDaisy`.
Works well on the console though, so we are skipping `preLaunchTask` (by commenting it)
And building from the command line.

```
//"preLaunchTask": "build_all_debug",
```

```console
$ make clean
rm -fR build
$ DEBUG=1 make
...
Memory region         Used Size  Region Size  %age Used
           FLASH:       88848 B       128 KB     67.79%
         DTCMRAM:          0 GB       128 KB      0.00%
            SRAM:       12424 B       512 KB      2.37%
          RAM_D2:       18392 B       288 KB      6.24%
          RAM_D3:          0 GB        64 KB      0.00%
         ITCMRAM:          0 GB        64 KB      0.00%
           SDRAM:          0 GB        64 MB      0.00%
       QSPIFLASH:          0 GB         8 MB      0.00%
arm-none-eabi-objcopy -O ihex build/HardwareTest.elf build/HardwareTest.hex
arm-none-eabi-objcopy -O binary -S build/HardwareTest.elf build/HardwareTest.bin
```

In the debugger, using `Cortex Debug`, `hw.StartLog` hangs, maybe waiting for a handshake.
Comment logging out.

```c++
hw.Init();
//hw.StartLog(true);
//hw.PrintLine("Daisy Patch SM started. Test Beginning");

/** Memory tests first to keep test short if everything else fails */
bool sdram_pass = hw.ValidateSDRAM();
//hw.PrintLine("SDRAM Test\t-\t%s", sdram_pass ? "PASS" : "FAIL");
bool qspi_pass = hw.ValidateQSPI();
//hw.PrintLine("QSPI Test\t-\t%s", qspi_pass ? "PASS" : "FAIL");
```

```c++
bool sdram_pass = hw.ValidateSDRAM();
// ❌ sdram_pass is false!

bool qspi_pass = hw.ValidateQSPI();
// ✅ qspi_pass is true
```

**Comment by ohmtech-rdi** [comment]
## Report 2

On Daisy Patch SM `rev2`.

Use USB to program the chip and communicate on serial.
Collect the serial output in 3 cases:
- After `make program-dfu`
   - Could never get the usbmodem to show up
- After pressing `RESET`
   - After several reset, usbmodem will eventually show up
- After a full power cycle
   - After several full power cycle, usbmodem will eventually show up

```console
$ cd DaisyExamples/patch_sm/HardwareTest
$ make clean
$ DEBUG=1 make
$ make program-dfu
dfu-util -a 0 -s 0x08000000:leave -D build/HardwareTest.bin -d ,0483:df11
dfu-util 0.10

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2020 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: Warning: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
Opening DFU capable USB device...
ID 0483:df11
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 1024
DfuSe interface name: "Internal Flash   "
Downloading element to address = 0x08000000, size = 97264
Erase      [=========================] 100%        97264 bytes
Erase    done.
Download   [=========================] 100%        97264 bytes
Download done.
File downloaded successfully
dfu-util: Error during download get_status
make: *** [program-dfu] Error 74
$ ls -l /dev/tty*
(no tty.usbmodem*)
(After several RESET or full power cycle:)
$ ls -l /dev/tty*
...
crw-rw-rw-  1 root  wheel   18,   8 Dec 16 10:45 /dev/tty.usbmodem365A375E32301
```

When tty appears in `/dev`, it is reported also in Arduino ports.

Select port and open serial monitor.

From Arduino Serial monitor, in all cases (program-dfu, RESET or full power cycle):

```
Daisy is online
===============
Daisy Patch SM started. Test Beginning
SDRAM Test   -   FAIL
QSPI Test   -   PASS
SDMMC Test   -   PASS
Streaming Test Results
######################
Analog Inputs:
CV_1:  0.999   CV_2:  0.999   CV_3:  0.999   CV_4:  0.999
CV_5:  0.999   CV_6:  0.999   CV_7:  0.807   CV_8:  0.999
ADC_9:  0.099   ADC_10:  0.122   ADC_11:  0.150   ADC_12:  0.114
######################
Digital Inputs:
Button: OFF   Toggle: DOWN   
GATE_IN_1: LOW   GATE_IN_2: LOW
######################
...
```

(For reference, I've put a SD card on my `kivu12` board, that's why the SDMMC test passes — which is also good news)
