### ISSUE TITLE
Test kivu12 rev3

### ISSUE THREAD

**Issue by ohmtech-rdi** [ohmtech-rdi/eurorack-blocks#214]
Test `kivu12` `rev3`

## Tasks

- [x] ~~Make `Kivu12Max` module?~~
   - Have all possible inputs/outputs in one module
   - Maybe no front plate
- [x] Order `kivu12` PCB
- [x] Order `drop` PCB
- [x] Order BOM, in particular
   - [x] BAT54SW
   - [x] Resistor for I2C
   - [x] All new pin sockets
- [ ] Assemble `kivu12`
- [ ] Assemble `drop`
- [ ] Test
