### ISSUE TITLE
Make an overview video and "Getting Started" guide

### ISSUE THREAD

**Issue by ohmtech-rdi** [ohmtech-rdi/eurorack-blocks#216]
The current state of the project doesn't include a call-to-action that would lead to a successful feeling in the 5-minutes and first-hour of evaluation milestones.

- Direct the user to first watch an overview video and then read the "Getting Started" guide,
- Add a less than 5 minutes overview video to show the end-to-end process of making a Eurorack module from conception to use in a Eurorack system,
- Add a less than 1 hour complete guide, to show in details the end-to-end process of making a Eurorack module from conception to use in a Eurorack system, with at least text and pictures, video at most.

As for strategy, first start by writing the guide and getting feedback about it, *before* we get into shooting the video, as it will be easier to integrate feedback for some text and pictures rather than a video edit.

## Chapters

- Overview
- Setting up dev environment
- Developing the software and testing in the simulator
- Ordering PCB/BOM and assembling `kivu12`
- Ordering PCB/BOM and assembling the module

## Tasks

- [x] Write "Getting Started" guide
- [x] Get feedback for "Getting Started" guide
- [x] Iterate "Getting Started" guide
- [ ] Write overview video script
- [ ] Get feedback for overview video script
- [ ] Shoot overview video draft
- [ ] Review draft & script
- [ ] Shoot overview video
- [ ] Integrate to project
