### ISSUE TITLE
Erbb meta-build System

### ISSUE THREAD

**Issue by ohmtech-rdi** [ohmtech-rdi/eurorack-blocks#238]
The current build system is far from optimal. This is the feedback we have for the moment and how to address it:

## Problems with Current Build system

- `gyp` is not famous compared to `cmake`
- Generated targets contain noise
   - Daisy targets are now only relevant to the erb contributor/maintainer, not the user
- `SdRam` depends on `erb_TARGET_XXX`
- `data` feature is in the `erbui` language but should be part of build system, because it doesn't represent a UI element
- Boilerplate `configure.py` and `build.py` scripts in each module

## What Users Want

- They want to get started with a new project idea quickly
   - Being able to create a new module skeleton quickly is a potential solution
- They want the project "simple"
   - Move away project commands such as configure or build which are just noise
   - Avoid the "what target should I build" IDE problem and noise
   - Target IDE subtleties is noise, so abstract it away
   - Not so much code to compile so we can put everything in one target to minimize project complexity/noise
- They still want a concept of "library" to group sources and resources logically
   - Usually per folder, typically a DSP library
   - But they don't need to have a proper target for it, as there is no need to share targets
      - As we have only one module in a project anyway
- They want to specify whether their code will be in Flash or QSPI
   - But this would be even better if automated, if possible
- They want to specify where to fetch their static data
   - But this would be even better if automated, if possible

## What Contributors/Maintainers Want

- They want to be able to have all the project sources for both Daisy and simulator targets in one project

## `erbb` Language 

`cmake` coud be something, but we have lots of very specific things for cross-compiling that would make the syntax most likely cryptic.

Instead of that, we will roll out a small language that takes into account everything upper.

```
module Kick {
   location flash    // or qspi

   import "../dsp/dsp.erbb"
   
   define erb_SDRAM_MEM_POOL_SIZE=1234
   define erb_SDRAM_MEM_POOL_SIZE_SIMULATOR_CHECK=0
   
   sources {
      file "Kick.cpp"
      file "Kick.h"
   }
   
   resources {
      // for now location is the same as module
      data body AudioSample { file "body.wav" }
      data transient01 AudioSample { file "transient01.wav" }
   }
}
```

`dsp.erbb`
```
define SOMETHING=1

// not sure yet which term for header search path
search ".."
base ".."
origin ".."
root ".."
include ".."
directory ".."

sources {
   file "Filter2Poles.cpp"
   file "Filter2Poles.h"
}

resources {
   // resources for an oscillator for example
}
```

## `erbb` Command Line Interface

We would have a command line `erbb`.

### Usage

Create everything to be able to build (IDE project, and all genrated code/graphic resources):
```console
$ erbb configure
```
This would also install all binary dependencies if needed. `erbb setup` could also force it.

Build the firmware:
```console
$ erbb build
```

Install the bootloader:
```console
$ erbb install bootloader
Press RESET + BOOT and hit any key to start the bootloader install
...
```

Install the firmware:
```console
$ erbb install
Press RESET and hit any key to start the bootloader install
...
```

### Install

Somehow, `erbb` needs to be in the `PATH`.

Either:
- Make a script to `source` it
- Or, gives instructions to add `erbb` to the `PATH`
- Or, a combination of both, to `source` it from `.profile` or `.bash_profile`

## Tasks

- [x] Reduce number of targets (in the `gyp` sense) in a project
- [x] Implement `erbb` language
- [x] Add `erbb` Xcode syntax highlighter
- [x] Add `erbb` simulator `gyp` generator
- [x] Add `erbb` Daisy `gyp` generator
- [x] Add `erbb` VSCode `gyp` generator
- [x] Add `erbb` command line and env init sourcing script
- [x] Cleanup unused scripts and gyp files
- [x] Add language documentation
